basePath: /{{replace_BasePath}}
consumes:
    - application/json
info:
    description: |-
        ## {{replace_TitleProjectSmallDescription}}

        {{replace_ProjectDescription}}
    title: '{{replace_ProjectName}}'
    version: '{{replace_ProjectVersion}}'
paths:
    /ping:
        get:
            description: '## A simple router to check server status'
            operationId: Ping
            responses:
                "200":
                    description: "Pong ! \U0001F94E"
                    schema:
                        $ref: '#/responses/success/schema'
            summary: Ping Pong!
            tags:
                - Ping
produces:
    - application/json
responses:
    accessDenied:
        description: ""
        schema:
            properties:
                message:
                    example: access is denied
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    badRequest:
        description: ""
        schema:
            properties:
                message:
                    example: bad request
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    conflict:
        description: ""
        schema:
            properties:
                message:
                    example: conflict
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    internalServer:
        description: ""
        schema:
            properties:
                message:
                    example: internal server error
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    notFound:
        description: ""
        schema:
            properties:
                message:
                    example: notFound
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    notImplementation:
        description: ""
        schema:
            properties:
                message:
                    example: not implementation
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    retryLimitExceeded:
        description: ""
        schema:
            properties:
                message:
                    example: retry limit exceeded
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    somethingWentWrong:
        description: ""
        schema:
            properties:
                message:
                    example: something went wrong
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    success:
        description: ""
        schema:
            properties:
                message:
                    example: success
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
    unauthorized:
        description: ""
        schema:
            properties:
                message:
                    example: unauthorized
                    type: string
                    x-go-name: Message
                payload:
                    example: "null"
                    x-go-name: Payload
            type: object
securityDefinitions:
    bearer:
        in: header
        name: Authorization
        type: apiKey
swagger: "2.0"
